# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 18:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20171008_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 8, 18, 2, 15, 898549, tzinfo=utc)),
        ),
    ]
