# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20171008_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='description',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='notes',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
